### ISSUE TITLE
Investigate pipeline technologies/approaches

### ISSUE THREAD

**Issue by gnomeoday** [gnomeoday/jawnzapp#8]
**Should be completed before #2** 

Check what is best pipeline approach for effective and efficient development and deployments.
Keep in mind CI/CD and QA.
Also it should be cheap if not completely free.
Heroku has number of approaches including CI and pipelines but CI is paid and I think Team deployments are also paid for dynos. Gitlab has free CI. Github actions might be worth a look, be nice to keep it with the code on github instead of another third party.  
**_Compare all pricing._**
Heroku pipeline feature seems very cool with github.
Should we deploy as docker pushed from github/gitlab CI/CD or direct from github to Heroku???

**Comment by run-crash-run** [comment]
Github Actions:
Actions:

Steps to set up:
Add a yaml file to .github/workflows and then add whatever commands we need to it

Info:
https://docs.github.com/en/free-pro-team@latest/actions/quickstart

**Pricing:
https://github.com/pricing
(Free - 2,000 mins a month)
($4 - 3,000 mins a month) *this looks to be a temporary reduction to get people to use it
($21 - 50,000 mins a month)**

Notes:
- Supported OS are Ubuntu, Windows and MacOS out of the box:(https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners)
- You can roll your own runner if you need a different flavour (https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners)
- Can integrate with Docker without too much effort: (official docker support) https://github.com/marketplace/actions/build-and-push-docker-images
- works with mvn out of the box: https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-maven
- can run jobs in parallel out of the box
- Can set the spending limit so we don't accidentally go over; (https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/managing-your-spending-limit-for-github-actions)
- Can install spark using plugin (https://github.com/marketplace/actions/setup-apache-spark)


Useful links:
(Use actions to create instance on heroku) https://medium.com/@michaelekpang/creating-a-ci-cd-pipeline-using-github-actions-b65bb248edfe
(Explaining the terms) https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions
(Java and maven) https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-maven
(Node) https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
(Generate files for pipeline) https://www.jhipster.tech/setting-up-ci/

**Comment by run-crash-run** [comment]
Gitlab:

Steps to set up:
add .gitlab-ci.yml to the root folder and add the steps to it

Info:
https://docs.gitlab.com/ee/ci/pipelines/

**Pricing:
https://about.gitlab.com/pricing/#gitlab-com
(Free - 400 minutes)
($4 - 2000 minutes)
($19 - 10,000 minutes)
($99 - 50,000 minutes)**

Notes:
- we use "shared runners" by default, can register another machine though: https://docs.gitlab.com/runner/install/
- can use templating (eg we have a template and then add whatever steps are different for local deploy or release)
- analysis tools for trying to figure out the dependencies between jobs: https://docs.gitlab.com/ee/ci/directed_acyclic_graph/index.html


Useful links:
(Interesting things to muck about with) https://gitlab.com/jawnteam/jawnzapp/-/settings/ci_cd
(Integrations (basically a webhook)) https://gitlab.com/jawnteam/jawnzapp/-/settings/integrations

**Comment by run-crash-run** [comment]
Heroku:

Steps to set up:
Either via the UI (pipelines > new pipeline) or via the CLI tool (pipelines:create)

Info:
https://devcenter.heroku.com/articles/pipelines

Pricing: (Note: Pricing is based on time rather than usage, even if the resource is active but lying idle)
I'm a bit confused by the docs, this line implies that if you have the free one it can't sleep - "Apps that only utilise a free worker dyno do not sleep, because they do not respond to web requests. Be mindful of this as they may run 24/7 and consume from your pool of hours."
(Also not sure if we can manually set the dyno to sleep, if we ran tests for 2 minutes and then got docked 30 minutes usage til it went to sleep that wouldn't be ideal)

There's a bunch of prices and articles and they all seem to contridict: 
https://devcenter.heroku.com/articles/heroku-ci#costs (This implies once you enable CI you have to pay 10 dollars a month)
https://devcenter.heroku.com/articles/free-dyno-hours (Not mentioned there but the free dyno hours total 550 hours)
https://devcenter.heroku.com/categories/billing
https://www.heroku.com/pricing


Notes:
- if we don't pick this one but are hosting on heroku, we could still potentially make use of the release phase to automate things like tagging or rolling back if we goof: https://devcenter.heroku.com/articles/release-phase


Useful links:
(Configuring CI) https://devcenter.heroku.com/articles/heroku-ci
(all the dev centre stuff) https://devcenter.heroku.com/articles
